// const name= "Vandana"
// const Age =23
// // console.log(name + Age + "value")
// console.log(`My name is ${name} and age is ${Age}`)
const name = new String('Vandana')
// console.log(name[0])
// console.log(name[1])
// console.log(name[2])
// console.log(name[3])
// console.log(name[4])
// console.log(name[5])
// console.log(name[6])
// console.log(name.length)
// console.log(name.toUpperCase())
// console.log(name.charAt(5))
// console.log(name.indexOf('d'))
// const newString = name.substring(0,4)
// console.log(newString)
const newString = name.slice(-7,6)
console.log(newString)